### ISSUE TITLE
make doc_html fails because 'no such file / directory' 

### ISSUE THREAD

**Issue by ericwomer** [PeterFeicht/cppreference-doc#39]
After downloading the prepared archive and unzipping it in the root of cppreference-doc then running make doc_html I get this error

```
make doc_html
mkdir -p output
./preprocess.py --src reference --dst output/reference
Traceback (most recent call last):
  File "/usr/lib/python3.11/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'output/reference/upload.cppreference.com/mwiki' -> 'output/reference/common'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eric/src/Manuals/cppreference-doc/./preprocess.py", line 84, in <module>
    main()
  File "/home/eric/src/Manuals/cppreference-doc/./preprocess.py", line 46, in main
    preprocess.rearrange_archive(root)
  File "/home/eric/src/Manuals/cppreference-doc/commands/preprocess.py", line 59, in rearrange_archive
    shutil.move(os.path.join(root, 'upload.cppreference.com/mwiki'), data_path)
  File "/usr/lib/python3.11/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/reference/upload.cppreference.com/mwiki'

```
and if I run make doc_html again it says nothing to be done for doc_html.

**Comment by diego-est** [comment]
`make doc_html` worked for me after running `make source`. It seems to not be the "preferred~" way of doing this but at least it works.

**Comment by PeterFeicht** [comment]
That is clearly explained in the README.

**Comment by ericwomer** [comment]
Thank you, you can close this issue now.
